AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  DisplayStyleGuide: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  Exclude:
    - "bin/**/*"
    - "cache/**/*"
    - "vendor/**/*"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"


# -------[ Layout ]-------

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/CaseIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true


# -------[ Lint ]-------

Lint/RequireParentheses:
  Enabled: true


# -------[ Style ]-------

Style/AndOr:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/UnneededPercentQ:
  Enabled: true


# -------[ Metrics ]-------

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 40
  Exclude:
    - "spec/**/*_spec.rb"
